defaults: &defaults
  docker:
    - image: yshui/comptonci
cached-checkout: &ccheckout
just-build: &build

version: 2.1
jobs:
  build:
    <<: *defaults
    parameters:
      build-config:
        type: string
        default: -Dbuild_docs=true
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: config
          command: meson << parameters.build-config >> -Dwerror=true . build
      - run:
          name: build
          command: ninja -C build
  test-xvfb:
    <<: *defaults
    steps:
      - run:
          name: xxx
          command: xvfb-run -s "-screen 0 640x480x24" glxinfo

workflows:
  all_builds:
    jobs:
      - build
      - build:
          build-config: -Dopengl=false -Ddbus=false -Dregex=false -Dconfig_file=false
      - build:
          build-config: -Dopengl=false
      - build:
          build-config: -Dregex=false
#     - test-xvfb
